language: node_js
node_js:
- '0.10.32'
deploy:
  provider: npm
  sudo: false
  email: romanornr@gmail.com
  api_key:
    secure: CGFlZdw7O8VjJgNalDpxNVMiNObEz1Sy91utY296nl+AOjFJHtmiW3uPnGc+LMXz69rLqdcUKQH2NO3I26csHIhXAU40W6lZ5m57ZaXqllm7Th4/SEVD/lK0wP9AMBKsY6qy82BNNIe2BGBIz5xSlzAQnEUGgEf5el02Z3ZHeOno01cZaZeUNgSd1UxgTVA4RqIYPQZnwvrcusDLONJLNBQ4EtrSvdkFuRLeVZvKX9VIRrv3vQ6nR8OtczJMR/YF3MBODpW8yY8zX2NXZdIzekDfXadNymYoJ4ICfFhLWYzC2PWLVr3FazV2MMgoI43DIsagmKpFnmvDB33FCHlesj844/oVq5AwYIhxhF7vyUK08guWM3bQkgeltTqwk3PhQPDbr8sZuIqfSFfZ5IbIIi4BOtX6iMKdJ9UBqpiqZdKig4A0taLp8njUdqXz1EGoFX0Qi/EHkLM04ZHil9nIvX2oFgkV5zG6qDK4YZydPlLpmYLpkuPvUxoISmbo1VwqCPh98evVaY+WRbgO9oZFqSr9v1FnnGziDR4xZOIIiHOjLu2J7i+fzfBPsJpXc31NnwdxE2VoALeG805pzirGwhIC9VQFWKCttaReyNDNvqKvBzel0JvVIZx2FagbMaLzFdh+DOoxBh9u7CWEWJP2wOiH4QpPW6tzQIDgTz+LHo4=